# Generated by Django 4.1.3 on 2023-01-04 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_comment_created_date_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='appreciated',
            field=models.ManyToManyField(related_name='posts', through='core.UserPostRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
