# Generated by Django 4.1.3 on 2023-01-04 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_appreciated_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default='2023-01-05'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 1, 5)),
        ),
        migrations.AlterField(
            model_name='userpostrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Not bad'), (3, 'Normal'), (4, 'Good'), (5, 'Very good')], null=True),
        ),
    ]
